In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Argentina' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 nan]
 ['Germany' 40.0 63777.0]
 ['Argentina' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['Argentina' nan 79000.0]
 ['Germany' 50.0 83000.0]
 ['Argentina' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [6]:
print(x)

[['Argentina' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 64086.333333333336]
 ['Germany' 40.0 63777.0]
 ['Argentina' 35.0 58000.0]
 ['Spain' 38.0 52000.0]
 ['Argentina' 37.666666666666664 79000.0]
 ['Germany' 50.0 83000.0]
 ['Argentina' 37.0 67000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 64086.333333333336]
 [0.0 1.0 0.0 40.0 63777.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 37.666666666666664 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [12]:
print(x_train)

[[0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 40.0 63777.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 64086.333333333336]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 37.666666666666664 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [15]:
print(y_test)

[0 1]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [17]:
print(x_train)

[[0.0 0.0 1.0 -0.11377156580310907 -1.1182574118854924]
 [0.0 1.0 0.0 0.20746579646449514 -0.1038692063762959]
 [1.0 0.0 0.0 0.8499405209997036 0.6044023580205898]
 [0.0 0.0 1.0 -0.11377156580310907 -0.07722540193508162]
 [0.0 0.0 1.0 -1.8805770582749324 -1.4627893658667088]
 [1.0 0.0 0.0 -0.1673111261810435 1.2073332774877186]
 [0.0 1.0 0.0 1.8136526078025164 1.551865231468935]
 [1.0 0.0 0.0 -0.5956276092045154 -0.6014594809136677]]


In [18]:
print(x_test)

[[0.0 1.0 0.0 -1.398721014873526 -0.9459914348948841]
 [1.0 0.0 0.0 -0.27439024693691116 0.17373741554406924]]
